# These are supported funding model platforms
github: [otabekoff]
# patreon: user
# open_collective: project
# ko_fi: user
# tydelift: platform/package
# community_bridge: project
# liberapay: user
# issuehunt: project
# lfm: project
# custom: ['https://example.com']
